### ISSUE TITLE
format_list() unicode character does not print correctly

### ISSUE THREAD

**Issue by DesiQuintans** [elbersb/tidylog#21]
- tidylog 0.1.0
- R 3.5.2

The character used to indicate a truncated list in `format_list()` is a unicode character that does not print correctly with any of the fonts I've tried. When I render my document to an HTML Notebook, it creates this: 

㠼㸵

And in RStudio it just appears as the 'missing symbol' diamond glyph.

**Comment by elbersb** [comment]
Strange. Are you on Windows?

I just committed these changes, so the package now uses the `clisymbols` package to print the ellipsis: https://github.com/elbersb/tidylog/commit/2a26b289362b4b5ab11f82405b5ed0e266a9d54a
Can you try the development version and let me know if that fixes the issue? Thanks!

**Comment by DesiQuintans** [comment]
Yes, I'm on Windows.

```
Windows 7 64-bit and Windows 10 64-bit
RStudio Preview 1.2.1322 (default text encoding is UTF-8)
```

I reinstalled from GitHub (tidylog v 0.1.0.90000) and can confirm the code change in my installed version, but the issue persists. The ellipsis still gets encoded as 㠼㸵 in HTML and shows the diamond glyph in RStudio (but it gets replaced with 3 dots in LaTeX).

The interesting thing is that my fonts are perfectly capable of displaying the ellipsis:

![image](https://user-images.githubusercontent.com/3200601/54241623-ae57f180-4575-11e9-9c9e-d92fbd1fed8c.png)

![image](https://user-images.githubusercontent.com/3200601/54241661-d7788200-4575-11e9-81f3-aa50607ba6ad.png)

**Comment by elbersb** [comment]
That's really odd! Honestly, I don't have much of an idea what could cause this. It must be something that the R package is doing...
What's your output of `l10n_info()` and `sessionInfo()$locale`?

**Comment by elbersb** [comment]
Just another idea I had: I removed the ellipses from the documentation. Maybe that's what messed with the package encoding (https://github.com/elbersb/tidylog/commit/9c1faec01840eab860411b2cf17ae3391f020cb4). Can you give it another try? 
If that doesn't help, could you remove `Encoding: UTF-8` from the `DESCRIPTION` file and reinstall the package locally?

**Comment by DesiQuintans** [comment]
Okay, this appears to be an issue with RMarkdown and not you. Can you reproduce this?

1. Create a new R Notebook and replace its contents with this the code that I provide below. 
2. Make sure that _Chunk Output Inline_ is enabled (it is by default).
3. Execute the chunks. The ellipsis character will be shown in the inline results pane, and also in the R console.
4. Now copy `invisible(select(df, a))`, paste it into the console, and run it there. The ellipsis should print just fine.

---


    ---
    title: "R Notebook"
    output: html_notebook
    ---
        
    ```{r setup}
    library(dplyr)
    library(tidylog)
    ```
    
    
    ```{r}
    df <- 
        data.frame(
            a = runif(10),
            b = runif(10),
            c = runif(10),
            d = runif(10),
            e = runif(10),
            f = runif(10),
            g = runif(10)
        )
    
    invisible(select(df, a))
    ```

**Comment by elbersb** [comment]
I cannot reproduce this. The ellipsis prints just fine in all cases.

What happens when you manually set your locale?

```
Sys.setlocale("LC_ALL", 'en_US.UTF-8')
```

Did you also check these things from above?

> Just another idea I had: I removed the ellipses from the documentation. Maybe that's what messed with the package encoding (9c1faec). Can you give it another try?
> If that doesn't help, could you remove Encoding: UTF-8 from the DESCRIPTION file and reinstall the package locally?

**Comment by elbersb** [comment]
Maybe the problem is that your RStudio encoding is different than your system encoding (which seems to be Latin1)?

**Comment by elbersb** [comment]
Any update on this?
